language: minimal

cache:
    directories:
        - $TRAVIS_BUILD_DIR/modules
        - $TRAVIS_BUILD_DIR/tools

services:
  - docker

before_install:
- docker pull maz3max/coinbuild

before_script:
  # Fetch the base branch when it is not `master`
- git fetch origin "${TRAVIS_BRANCH}:${TRAVIS_BRANCH}"

script:
- docker run -i -t -u $UID -v $(pwd):/data/build maz3max/coinbuild
- export COMMIT=$(git log --format=%h -1)
- export DEPLOY_FILE=prod-g${COMMIT}.zip
- zip ${DEPLOY_FILE} prod/coin.hex prod/central.hex prod/gen_bond.py prod/requirements.txt

deploy:
  - provider: releases
    api_key:
      secure: $GITHUB_API_KEY
    file:
    - ${DEPLOY_FILE}
    skip-cleanup: true
    prerelease: true
    on:
      repo: maz3max/ble-coin
