language: c
cache:
  directories:
  - "$TRAVIS_BUILD_DIR/modules"
  - "$TRAVIS_BUILD_DIR/tools"
services:
- docker
before_install:
- docker pull maz3max/coinbuild
before_script:
- git fetch origin "${TRAVIS_BRANCH}:${TRAVIS_BRANCH}"
script:
- docker run -i -t -u $UID -v $(pwd):/data/build maz3max/coinbuild
- export COMMIT=$(git log --format=%h -1)
- export DEPLOY_FILE=prod-g${COMMIT}.zip
- zip ${DEPLOY_FILE} prod/coin.hex prod/central.hex prod/gen_bond.py prod/requirements.txt
deploy:
  - provider: releases
    api_key:
        secure: BHWpeKOXMyuYXHju2V9uogkHIARKQiG8LCeI5l4Gorqt1g7hIfrBT2G71risNQfCZm2ICmmKwIeqGamNYxTTMpweI9Bfzlv1NPYFHamI8YfsYY0o4igt4kqlXeWmRoU/+1BvRWRH6Dn1wmtHvuyU+Oq98q9tjH0jFCo192ECg9vJMmVh/viRCL0ZVyrzomDANqBaCfLonGTVvN6HF1ixDUMs3hrIQnWiymCtYzIhQs+SRDPYxJvcTCMM1D1jI8VPm0/4Fhqfc5HMk8Dg7jTm+fIO4PkEqjDKvliFY99d4cvZb2bXEfnJtSUkHVsDWrRkxWLrMnI2TB2BCsODBdRWbdXkf2l3RErQuiL6MOr802eEEMfmwjv7TOv3Hd1YJcFGG/nRu5//rboXtxkEdXge+9ehUv78m/3eZkhazg/tnhAg+tFS8m7X2qGNzYiU5kNiRZUpw0DtDUO6pGeWiHNW9d0B+KgnpD9Ysb5v8eP2eVbzeN0oAV4iMpO7z8ww0hR8jXxfSk6fF6dEVcKk3ARVewDIQrQ039keIoQtIgnRTfUBI028km6fExxr5NwOmEOe/qtEOJTnRrTC7r2SB4FesYfy99xD3P6FHCDDgowNPMIYph28UUTYXH1MpdLDU/ySGNyDgBA/+vz047ixqPsLH16tVakdV+Sf3KSeQ1RmYhU=
    file:
    - ${DEPLOY_FILE}
    skip-cleanup: true
    prerelease: true
    on:
      repo: maz3max/ble-coin
